# Numpy

In [1]:
import numpy as np

## 1D Array

In [2]:
a= np.array([1,2,3,4,5])

In [3]:
a

array([1, 2, 3, 4, 5])

In [4]:
print(type(a))

<class 'numpy.ndarray'>


## 2D Array

In [5]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 3D array

In [7]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [8]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [9]:
d=np.array(c,dtype=float)

In [10]:
d

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

### Numpy Attributes

In [12]:
print(a)
print(b)
print(c)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [14]:
print(a)
print(a.shape)
print(a.ndim)
print(a.itemsize)
print(a.dtype)
print(a.size)

[1 2 3 4 5]
(5,)
1
8
int64
5


In [15]:
np.__version__

'2.1.3'

In [16]:
print(b)
print(b.shape)
print(b.ndim)
print(b.itemsize)
print(b.dtype)
print(b.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2
8
int64
9


In [17]:
print(c)
print(c.shape)
print(c.ndim)
print(c.itemsize)
print(c.dtype)
print(c.size)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
3
8
int64
8


### Arrange Function

In [19]:
a=np.arange(12)
b=np.arange(1,4)
c=np.arange(1,8,2)
print(a)
print(b)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[1 2 3]
[1 3 5 7]


### Scalar operation

In [20]:
print(a*3)
print(a+3)
print(a-3)
print(a/3)
print(a//3)
print(a**3)

[ 0  3  6  9 12 15 18 21 24 27 30 33]
[ 3  4  5  6  7  8  9 10 11 12 13 14]
[-3 -2 -1  0  1  2  3  4  5  6  7  8]
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.         3.33333333 3.66666667]
[0 0 0 1 1 1 2 2 2 3 3 3]
[   0    1    8   27   64  125  216  343  512  729 1000 1331]


## Reshape
- It changes the dimentions of a given array provided by the parameter

In [21]:
a= np.arange(12).reshape(3,4)

In [22]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
a= np.arange(12).reshape(3,3)

ValueError: cannot reshape array of size 12 into shape (3,3)

In [24]:
a= np.arange(12).reshape(3,2,2)

In [25]:
a

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

## numpy.nditer

In [26]:
print(a)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


## Iterating through the array

In [30]:
for i in a:
    print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]
[[ 8  9]
 [10 11]]


In [29]:
for i in a:
    for j in i:
        for k in j:
            print(k)

0
1
2
3
4
5
6
7
8
9
10
11


In [31]:
for i in np.nditer(a):
    print(i,end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 

In [33]:
x=np.array([1,2,3])
y=np.array([4,5,6])
x+y

array([5, 7, 9])

### ndenumerate    
-  not in syllabus

In [34]:
for i,j in np.ndenumerate(a):
    print(i,j)

(0, 0, 0) 0
(0, 0, 1) 1
(0, 1, 0) 2
(0, 1, 1) 3
(1, 0, 0) 4
(1, 0, 1) 5
(1, 1, 0) 6
(1, 1, 1) 7
(2, 0, 0) 8
(2, 0, 1) 9
(2, 1, 0) 10
(2, 1, 1) 11


## np.concatenate
- It joins two given array at given axis

In [35]:
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [36]:
np.concatenate((c,d))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [37]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [38]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [39]:
np.concatenate((c,d),axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

## `np.array_split`
- it opposite to join,will split the given into given split
- Split conditions- For an array of length l that should be split
    into n sections, it returns l % n sub-arrays of size l//n + 1
    and the rest of size l//n.

In [40]:
np.array_split(np.array([1,2,3,4,5,6,7]),3)

[array([1, 2, 3]), array([4, 5]), array([6, 7])]

## `np.where`
- it returns the indices of the given array where the given condition is satisfied

In [42]:
a=np.array([40,34,67,56,45,87,12,68])

In [43]:
np.where(a>50)

(array([2, 3, 5, 7]),)

## `np.sort`
- It sorts the array 

In [44]:
a=np.array([40,34,67,56,45,87,12,68])
np.sort(a)

array([12, 34, 40, 45, 56, 67, 68, 87])

In [53]:
b=np.array([[5,1,3],[4,3,7],[2,6,4]])

In [54]:
np.sort(b)

array([[1, 3, 5],
       [3, 4, 7],
       [2, 4, 6]])

In [55]:
print(b)

[[5 1 3]
 [4 3 7]
 [2 6 4]]


In [56]:
np.sort(b,axis=0)

array([[2, 1, 3],
       [4, 3, 4],
       [5, 6, 7]])

## Numpy Random module

### `random.randint`

In [57]:
from numpy import random

In [60]:
x=random.rand()
print(x)

0.8208727966787716


> Generate a 2D array with 3 rows randomly with 5 columns

In [63]:
x=random.randint(100,size=(2,5))
print(x)

[[85 96 32 92 65]
 [68 52 18 52 23]]


In [65]:
x=random.rand(2,5)
print(x)

[[0.51152227 0.03300484 0.83110878 0.40464315 0.06193961]
 [0.47462749 0.00192103 0.91052769 0.73586875 0.82158743]]


## `choice()`

In [68]:
x=random.choice([3,4,7,9],size=(4,5))
print(x)

[[9 4 7 9 3]
 [4 4 3 7 3]
 [7 7 3 4 9]
 [3 3 9 3 7]]
